### ISSUE TITLE
Compatible with level-sublevel?

### ISSUE THREAD

**Issue by pfraze** [cshum/sublevelup#3]
Is it possible for this to be compatible with https://www.npmjs.com/package/level-sublevel ?
That's the sublevel I'm using, and it's used a lot more by other packages too.

What's happening right now is, I'm passing a `level-sublevel` into levi and it's just giving an error.

**Comment by cshum** [comment]
@pfraze this is definitely worth looking into, in fact I was using level-sublevel heavily.

This exists because I want
* A sublevel that exposes a LevelUP instance https://github.com/mafintosh/subleveldown
* Keeping level-sublevel goodness such as `.sublevel()` method and `prefix: subdb` for `.batch()`
* Works with https://github.com/cshum/level-transactions

With these in mind, it seems easier to simply create another sublevel module. 

But compatibility with https://www.npmjs.com/package/level-sublevel is also important.
